{
  "language": "python",
  "os": [
    "windows"
  ],
  "dist": "xenial",
  "python": [
    "2.7"
  ],
  "install": [
    "cd ..",
    "wget http://www.renpy.org/dl/6.99.12/renpy-6.99.12-sdk.tar.bz2",
    "tar xf renpy-6.99.12-sdk.tar.bz2",
    "rm renpy-6.99.12-sdk.tar.bz2",
    "cd renpy-6.99.12-sdk"
  ],
  "env": {
    "jobs": [
      {
        "SDL_AUDIODRIVER": "dummy"
      }
    ]
  },
  "script": [
    "./renpy.sh \"../4US/\" lint && ./renpy.sh launcher distribute \"../4US/\""
  ]
}
